name: pydamage_article
channels:
  - bioconda
  - conda-forge
  - maxibor
  - defaults
dependencies:
  - click=8.0.0
  - numpy=1.20.2
  - pandas=1.2.4
  - pip=21.1.1
  - pysam=0.16.0.1
  - python=3.9.4
  - streamlit=0.81.1
  - pydamage