# prokka 1.14.6

all: prokka
	@echo "Done"

prokka: 
	prokka --outdir ../../results/prokka --cpus 12 --prefix ZSM028 --metagenome ../../data/ZSM028.pydamage_filtered.fa
clean:
	rm -rf ../../results/prokka