name: pydamage
channels:
  - maxibor
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - biopython=1.78
  - bleach=3.3.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.5
  - click=7.1.2
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.4
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.2
  - icu=68.1
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - ipykernel=5.5.0
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - isa-l=2.30.0
  - jedi=0.17.2
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - kneed=0.7.0
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.0.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.60
  - numpy=1.19.5
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.0
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.7.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pigz=2.6
  - pillow=8.1.0
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pydamage=0.50beta
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-isal=0.7.0
  - python_abi=3.7
  - pytz=2020.5
  - pyzmq=22.0.3
  - qt=5.12.9
  - readline=8.0
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.34.0
  - statsmodels=0.12.1
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.55.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xopen=1.1.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.8